Don't use universal character names for control characters
When the Vala code is converted to C in the build process
the compiler (in this case clang) generates:

  error: universal character name refers to a control character

because "control characters (in ranges 0x0-0x1F and 0x7F-0x9F)
cannot be expressed in universal character names"
(see https://en.cppreference.com/c/language/escape)

This uses their hex representation instead
(split in tests/steam_test.vala to avoid the E of ELFfixture
being interpreted as part of the escape sequence)

Signed-off-by: Xarblu <xarblu@protonmail.com>